version: 2

updates:
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
  commit-message:
    prefix: ci
- package-ecosystem: cargo
  directory: /
  schedule:
    interval: weekly
  commit-message:
    prefix: chore(deps)
- package-ecosystem: rust-toolchain
  directory: /
  schedule:
    interval: weekly
  commit-message:
    prefix: chore(deps)
