name: Audit

on: pull_request

jobs:
  rust:
    name: Rust
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Audit Rust Dependencies
        run: |-
          make audit
